server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    # Ao abrir a raiz, redireciona para a home do portal
    location = / {
        return 302 /html/home.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
